### PR TITLE
IMPORTANT: Fix For First Aid

### PR DESCRIPTION
**Pull request by Belrand**
Core: First Aid doesn't scan in non English client, this fixes it

The toc edit is flavour

### CODE REVIEW

**Comment by Treeston** [comment]
> --Couldn't find proper one so I used the CN one, pls send message on discord if innacurate -Belrand

The PTR lets you set any locale in the launcher, fyi.

**Comment by Belrand** [comment]
Sadly, I am unable to distinguish between zhTW and zhCN locales ^^'

I can give a shot, but I'm unsure as to how I can copy the text from the game though

**Comment by Treeston** [comment]
`ChatFrame1EditBox:SetText((GetSpellInfo(...)))`, or something along those lines?

**Comment by Belrand** [comment]
I'm dumb, it's a skill, I can just link it in chat

Game returned 急救 in zhTW locale but it seems different IG 
image

**Comment by Belrand** [comment]
So "急救" does work!

image

I got a lot of Lua errors but none of them from Guildbook so I believe it's good!

**Pull request merged**
